### ISSUE TITLE
Open the src file if command is ran against the spec file

### ISSUE THREAD

**Issue by thekarel** [thekarel/vscode-open-spec-file#5]
I.e. don't create `src.spec.spec.js`

**Comment by jarekb84** [comment]
This is someone related to my comment in #6, but instead of doing nothing in this scenario, you could open the src.js file instead. 

Just hit this use case now when I ran my linter which complained bout something in my spec file. Upon opening the spec file, I realized I missed something and needed to open the src file. Woulda been a nice feature to just toggle from spec file to src file in this case.

**Comment by thekarel** [comment]
Yes, this makes sense, probably what most users would expect.

**Comment by thekarel** [comment]
Fixed in https://github.com/thekarel/vscode-open-spec-file/pull/7
